---
title: "map of reserve sites"
author: "sbsambado"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(raster)
library(dplyr)
library(spData)
#devtools::install_github("geocompr/geocompkg")
library(spDataLarge)

library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package
library(dismo)
library(scales)

library(ggmap)
library(tmaptools)
library(RCurl)
library(jsonlite)
library(tidyverse)
library(leaflet)
```

this is fig 1
```{r}
library(ggmap)
library(readr)
library(tidyverse)
library(janitor)
library(ggrepel)
library(ggtext)
library(sf)
library(raster)
library(dplyr)
library(spData)


# call in data

locations <- read_csv("FieldSeason21_plots.csv")

# add location coastal/inland to dataframe
locations$location <- locations$reserve

locations$location[locations$reserve == "McLaughlin"] <- "Inland"
locations$location[locations$reserve == "Quail Ridge"] <- "Inland"
locations$location[locations$reserve == "Point Reyes"] <- "Coastal"

locations$location[locations$reserve == "Fort Ord"] <- "Coastal"
locations$location[locations$reserve == "Hastings"] <- "Inland"
locations$location[locations$reserve == "Big Creek"] <- "Coastal"
locations$location[locations$reserve == "Rancho Marino"] <- "Coastal"

locations$location[locations$reserve == "Sedgwick"] <- "Inland"
locations$location[locations$reserve == "Coal Oil"] <- "Coastal"
locations$location[locations$reserve == "Stunt Ranch"] <- "Inland"
locations$location[locations$reserve == "Santa Cruz Island"] <- "Inland"


# clean names
locations <- locations %>%
  clean_names()

# create georeferrenced box
myLocation <- c(-123.9, 32, -115.5, 40.5)


# one type of map
#myMap <- get_map(location=myLocation, source="stamen", maptype="terrain", crop=FALSE) 


# going to go with satellite map
myMap2 <- get_map(location=myLocation, source="google", maptype="satellite") 



sm <- with(locations,c(lon=median(longitude),lat=median(latitude)))

# get map with appropriate zoom
sq_map1 <- get_map(location = sm, zoom=7,
                   source = "google", maptype = "satellite")

# make sure it's in the lat/lon formation that google likes
names(locations)[5] <- "lat"
names(locations)[6] <- "lon"

# going to only include my plots from my mathias project and selecting plot 1 from all those reserves to remove duplication on my map
locations <- locations[which(locations$project == "mathias"),]
locations <- locations[which(locations$plot_number == 1),]

# build main map
main<-ggmap(sq_map1) +
  geom_point(data=locations,aes(x=lon,y=lat,colour=factor(locations$location)),size = 4) +
  scale_color_manual(values = c("green","red"))+
    geom_label_repel(
      aes(x = lon, y = lat, label = reserve), data = locations[locations$reserve != "Stunt Ranch",],
      size = 4,
      box.padding = .6, max.overlaps = Inf,  
      direction = "both",
      xlim = c(-Inf,Inf),
      min.segment.length = 0,
      segment.size = 1) +
  coord_cartesian(clip = "off") +
  labs(x = "Longitude", y = "Latitude", color = "Location") +
  geom_textbox(data =locations[locations$reserve == "Stunt Ranch",], aes(x = lon, y = lat), label = "Stunt Ranch",
               vjust = -1,
               maxwidth = unit(2.58,"cm"),
               maxheight = unit(.7,"cm")) +
  theme(axis.title = element_text(face = "bold"),
        legend.justification = c(1,1), 
        legend.position = c(1,1), 
        legend.background = element_rect(fill = "white"),
        legend.title = element_text(face = "bold"),
        legend.text = element_text(siz = 9),
        legend.key = element_rect(fill = "transparent", color = "transparent"),
        legend.box.background = element_rect(color = "black")) +
  annotate("segment", x = -118.65, xend = -118.4, y = 34.1, yend = 34.32,
           color = "black", size = 1.1)
 ggsave("reserve.png")
 
 
       
## make insert map of CA
 
 usa <- map_data("usa") 
states <- map_data("state")
ca_df <- subset(states, region == "california")
ca_base <- ggplot(data = ca_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")


# make sure to use ggplotGrob for inserts
insert <- ggplotGrob(ca_base + theme_bw() +
  annotate("rect", xmin = -124, xmax = -118.4, ymin = 33, ymax = 39.1, color = "red", alpha = .01)+
  labs(x = "", y = "", title = "Map of California") +
  theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(size = 5),
        title = element_text(size = 8, face = "bold")))

## combine main map with insert map for final image
main +
  annotation_custom(grob = insert, xmin = -125, xmax = -123, ymin = 33.6, ymax = 36)
ggsave("reserves_insert.png")
```


