---
title: "prelim"
author: "sbsambado"
date: "5/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

```{r message = FALSE, warning = FALSE}


library(readr)
library(tidyverse)
library(ggplot2)

prelim <- read_csv("California Tick Data Base - Sheet1.csv")

levels(prelim$reserve)[levels(prelim$reserve) == "Sedgewick"] <- "Sedgwick"
levels(prelim$genus)[levels(prelim$genus) == "Haemphysalis"] <- "Haemaphysalis"


prelim <- subset(prelim, reserve != "Paradise Reserve")
prelim$reserve
prelim$month <- factor(prelim$month,
                       levels = c("January", "March", "April", "May", "June"))

unique(prelim$reserve)
unique(prelim$genus)
prelim$reserve <- factor(prelim$reserve,
                       levels = c("McLaughlin", "Quail Ridge", "Point Reyes",
                                  "Fort Ord", "Hastings", "Big Creek", "Rancho Marino",
                                  "Coal Oil Point", "Sedgwick", "Santa Cruz Island", "Stunt Ranch"))


library(devtools)
devtools::install_github("an-bui/calecopal")
library(calecopal)
names(cal_palettes)

cal_palette(name = "desert", n = 15, type = "continuous")

# scale_fill_manual(values = cal_palette("sierra1"))
# scale_color_manual(values = cal_palette("sierra1"))

prelim$guess <- prelim$life_stage

prelim$guess[prelim$life_stage == "ID"] <- "J"
prelim$guess[prelim$life_stage == "N"] <- "J"
prelim$guess[prelim$life_stage == "L"] <- "J"


```



```{r}

dim(prelim)


ggplot(prelim, aes(y = genus, x = month, fill = guess )) +
  geom_histogram(stat = "identity") +
  facet_wrap(~reserve) +
  theme_bw()

prelim$count <- prelim$genus
prelim$count <- 1

tick_counts <- aggregate(count ~ reserve + month + guess, data = prelim, FUN = sum)
aggregate(count ~ reserve, data = prelim, FUN = sum)

tick_counts_sp <- tick_counts[which(tick_counts$month != "January"),]
ggplot(tick_counts_sp, aes(x = reserve, y = count, fill = guess))+
  geom_histogram(stat = "identity") +
  facet_wrap(~ month) +
  labs(y = "Tick Counts",x =  "Reserve", 
       title = "Tick counts by month & reserve",
       fill = "Life Stage") +
  scale_x_discrete(limits = rev(levels(tick_counts$reserve))) +
  scale_fill_manual(values = cal_palette("collinsia", n = 2, type = "continuous"))+
  coord_flip() +
  theme_bw() +
  theme(legend.position = "bottom")
ggsave("TickCount_ReserveMonth_rough.jpeg", dpi = 320)

ggplot(tick_counts, aes(x = reserve, y = count))+
  geom_histogram(stat = "identity") +
  facet_wrap(~ month) +
  labs(y = "Tick Counts",x =  "Reserve", 
       title = "Tick counts by month & reserve",
       fill = "Life Stage") +
  scale_x_discrete(limits = rev(levels(tick_counts$reserve))) +
  scale_fill_manual(values = cal_palette("collinsia", n = 2, type = "continuous"))+
  coord_flip() +
  theme_bw() +
  theme(legend.position = "bottom")
ggsave("TickCount_ReserveMonth_rough.jpeg", dpi = 320)
```

summary
```{r}
# tick_counts <- aggregate(count ~ reserve + month + guess, data = prelim, FUN = sum)

library(dplyr)
library(tangram)
install.packages("purrrlyr")
library(purrrlyr)
library(gtsummary)
library(gt)


webshot::install_phantomjs()
tick_counts2 <- prelim %>%
  select(reserve,count) %>%
  tbl_summary() %>%
  modify_header(label ~ "**Tick Counts by Reserve**") %>%
  as_gt() %>%
  gt::gtsave(filename = "count_table.png")


```




### Lizard data
```{r}

liz <- read_csv("Mathias2021_FieldData_Lizard - Sheet1.csv")
dim(liz)

names(liz) <- c('reserve', 'round', 'date', 'liz', 'field_burden', 'site',"burden")

liz$round <- as.factor(liz$round)


liz$region <- liz$reserve

liz$region[liz$reserve == "McLaughlin"] <- "northern"
liz$region[liz$reserve == "Quail Ridge"] <- "northern"
liz$region[liz$reserve == "Point Reyes"] <- "northern"

liz$region[liz$reserve == "Fort Ord"] <- "central"
liz$region[liz$reserve == "Hastings"] <- "central"
liz$region[liz$reserve == "Big Creek"] <- "central"
liz$region[liz$reserve == "Rancho Marino"] <- "central"

liz$region[liz$reserve == "Sedgwick"] <- "southern"
liz$region[liz$reserve == "Coal Oil Point"] <- "southern"
liz$region[liz$reserve == "Stunt Ranch"] <- "southern"
liz$region[liz$reserve == "Santa Cruz Island"] <- "southern"


liz$reserve <- factor(liz$reserve,
                      levels = c("McLaughlin", "Quail Ridge", "Point Reyes",
                                 "Fort Ord", "Hastings", 
                                 "Big Creek", "Rancho Marino",
                                 "Sedgwick", "Coal Oil Point",
                                 "Stunt Ranch", "Santa Cruz Island"))



liz$location <- liz$region

liz$location[liz$reserve == "McLaughlin"] <- "inland"
liz$location[liz$reserve == "Quail Ridge"] <- "inland"
liz$location[liz$reserve == "Point Reyes"] <- "coastal"

liz$location[liz$reserve == "Fort Ord"] <- "coastal"
liz$location[liz$reserve == "Hastings"] <- "inland"
liz$location[liz$reserve == "Big Creek"] <- "coastal"
liz$location[liz$reserve == "Rancho Marino"] <- "coastal"

liz$location[liz$reserve == "Sedgwick"] <- "inland"
liz$location[liz$reserve == "Coal Oil Point"] <- "coastal"
liz$location[liz$reserve == "Stunt Ranch"] <- "inland"
liz$location[liz$reserve == "Santa Cruz Island"] <- "inland"


liz$month <- liz$date

liz$month[liz$round == "2"] <- "March"
liz$month[liz$round == "3"] <- "April"
liz$month[liz$round == "4"] <- "May"
liz$month[liz$round == "5"] <- "June"

liz$month <- factor(liz$month, 
                    levels = c("March", "April", "May", "June"))

liz$region <- factor(liz$region, 
                     levels = c("northern", "central", "southern"))


regioncolor = c('brown1','tan1','lightgoldenrod1')
locationcolor = c('darkseagreen1', 'brown')
```



```{r}

## ALL
ggplot(liz, aes(x = month, y = log(burden + 1))) +
  geom_boxplot() +
  geom_jitter(aes(color = reserve), alpha = .7, width = .1) +
  scale_color_manual(values = cal_palette("sierra1", n = 11, type = "continuous"))+
  labs(x = "Month",y =  "log(burden + 1)", title = "Lizard burdens across all sites" ) +
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  theme_classic() 
ggsave("LizBurdens_All.jpeg", dpi = 320)


## Region

ggplot(liz, aes(x = month, y = log(burden + 1)), color = region) +
  geom_boxplot() +
  geom_jitter(aes(color = region), alpha = .7, width = .1) +
  scale_color_manual(values = c('brown1','tan1','lightgoldenrod1'))+
  labs(x = "Month",y =  "log(burden + 1)", title = "Lizard burdens across regions" ) +
    theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  theme_classic() +
  theme(legend.position = "bottom")
ggsave("LizBurdens_Regions.jpeg", dpi = 320)

## LOCATION

ggplot(liz, aes(x = month, y = log(burden + 1))) +
  geom_boxplot() +
  geom_jitter(aes(color = location), alpha = .7, width = .1) +
  scale_color_manual(values = c('darkseagreen1', 'brown'))+
  labs(x = "Month",y =  "log(burden + 1)", title = "Lizard burdens across locations" ) +
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  theme_classic() +
  theme(legend.position = "bottom")
ggsave("LizBurdens_Location.jpeg", dpi = 320)
```

Show these plots
```{r warning = FALSE}
##### Lizard burden


## ALL
ggplot(liz, aes(x = month, y = log(burden + 1))) +
  geom_boxplot() +
  geom_jitter(aes(color = reserve), alpha = .7, width = .1) +
  scale_color_manual(values = cal_palette("sierra1", n = 11, type = "continuous"))+
  labs(x = "Month",y =  "log(burden + 1)", title = "Lizard burdens across all sites" ) +
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  theme_bw() 
#ggsave("LizBurdens_All.jpeg", dpi = 320)


## by region
ggplot(liz, aes(x = region, y = log(burden + 1)), color = region) +
  geom_boxplot() +
  facet_wrap(~ month) +
  geom_jitter(aes(color = reserve),alpha = .7, width = .1) +
  scale_color_manual(values = cal_palette("sierra1", n = 11, type = "continuous"))+
  #scale_color_manual(values = c('brown1','tan1','lightgoldenrod1'))+
  labs(x = "Region",y =  "log(burden + 1)", title = "Lizard burdens across regions" ) +
    theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  theme_bw() +
  theme(legend.position = "none")
  # theme(legend.position = "bottom")
ggsave("LizBurdens_RegionsFacet_v2.jpeg", dpi = 320)


## by location
ggplot(liz, aes(x = location, y = log(burden + 1)), color = region) +
  geom_boxplot() +
  facet_wrap(~ month) +
  geom_jitter(aes(color = reserve),alpha = .7, width = .1) +
  scale_color_manual(values = cal_palette("sierra1", n = 11, type = "continuous"))+
  #scale_color_manual(values = c('brown1','tan1','lightgoldenrod1'))+
  labs(x = "Location",y =  "log(burden + 1)", title = "Lizard burdens across locations" ) +
    theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  theme_bw() +
  theme(legend.position = "none")
  # theme(legend.position = "bottom")
ggsave("LizBurdens_LocationFacet_v2.jpeg", dpi = 320)


liz_counts <-liz %>%
  group_by(reserve, month) %>%
  summarise(freq = length(liz), .groups = 'drop')

ggplot(liz_counts, aes(y = freq, x = reserve, fill = month)) +
  geom_histogram(stat = "identity")+
  labs(y = "Counts of Lizards",x =  "Reserve", 
       title = "Lizard counts by month & reserve",
       fill = "Month") +
  scale_x_discrete(limits = rev(levels(liz_counts$reserve))) +
  scale_fill_manual(values = cal_palette("oak", n = 3, type = "continuous"))+
  coord_flip() +
  theme_bw() 
#ggsave("LizNumbers_ReserveMonth.jpeg", dpi = 320)
```


```{r}



ggplot(liz, aes(x = month, y = log(burden), fill = reserve)) +
  geom_boxplot() +
  geom_jitter(alpha = .5) +
  scale_fill_manual(values = cal_palette("sierra1", n = 11, type = "continuous"))+
  theme_classic()

library(ggthemes)

ggplot(liz, aes(x = month, y = log(burden), fill = reserve)) +
  geom_boxplot() +
  geom_jitter(alpha = .5) +
  #scale_color_calc()
  scale_color_continuous_tableau()+
  theme_classic()



```



```{r}
ggplot(liz, aes(x = month, y = log(burden + 1))) +
  geom_boxplot() +
  facet_wrap(~reserve) +
  theme_classic()

ggplot(liz, aes(x = month, y = log(burden + 1))) +
  geom_boxplot() +
  facet_wrap(~region, scale = "free_y",ncol = 1) +
  geom_jitter(aes(color = reserve))+
  theme_bw()

ggplot(liz, aes(x = month, y = log(burden))) +
  geom_boxplot() +
  facet_wrap(~location, ncol = 1) +
  geom_jitter(aes(color = reserve))+
  theme_bw()


liz$julian <- as.Date(liz$date, format = "%m/%d/ %y")

liz$julian <- format(liz$julian, "%j")

liz$julian <- as.numeric(liz$julian)
ggplot(liz, aes(x = julian, y = log(burden +1 ), color = location))+
  geom_point() +
    scale_color_manual(values = c('darkseagreen4', "tan"))+
  geom_smooth(se = FALSE)

ggplot(liz, aes(x = julian, y = burden, color = reserve)) +
  geom_jitter(alpha = .5) +
  facet_wrap(~ location, scale = "free_y",ncol = 1) +
  theme_light() +
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  labs(y = "Lizard burdend", x = "Julian Date", color = "Reserve")

ggplot(liz, aes(x = month, y = log(burden +1 ))) +
    geom_boxplot()+
  geom_jitter(alpha = .5, aes(color = reserve)) +
  facet_wrap(~ location, scale = "free_y",ncol = 1) +
  theme_light() +
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  labs(y = "Lizard burdend", x = "Julian Date", color = "Reserve")


ggplot(liz, aes(x = month, y = log(burden +1 ))) +
    geom_boxplot()+
  geom_jitter(alpha = .5, aes(color = reserve)) +
  facet_wrap(~ region,ncol = 1) +
  theme_light() +
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  labs(y = "Lizard burdend", x = "Month", color = "Reserve")

ggplot(liz, aes(x = month, y = log(burden +1 ))) +
    geom_boxplot()+
  geom_jitter(alpha = .5) +
  facet_wrap(~ region,ncol = 1) +
    theme_minimal() +
  theme(strip.background = element_rect(fill = 'gray95'))+
  theme(strip.text.x = element_text(face = 'bold'))+
  theme(legend.text = element_text(size = 5),
        legend.title = element_text(size = 6),
        axis.title.x = element_text(size = 7)) +
  labs(y = "Lizard burdend", x = "Month", color = "Reserve")


burdens_site <-aggregate(burden ~ reserve, data = liz, FUN = sum)

burdens_site$reserve <- factor(burdens_site$reserve,
                      levels = c("McLaughlin", "Quail Ridge", "Point Reyes",
                                 "Fort Ord", "Hastings", 
                                 "Big Creek", "Rancho Marino",
                                 "Sedgwick", "Coal Oil Point",
                                 "Stunt Ranch", "Santa Cruz Island"))


aggregate(burden~ month, data = liz, FUN = sum)

burdens_month <-aggregate(burden ~ month + region, data = liz, FUN = sum)


 
ggplot(burdens_site, aes(x = burden, y = reserve)) +
  geom_histogram(stat = "identity") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5)) 

ggplot(burdens_month, aes(y = burden, x = month)) +
  geom_histogram(stat = "identity") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5)) 



ggplot(liz, aes(x = month, y = log(burden + 1))) +
  geom_boxplot() +
  facet_wrap(~reserve)

```
devtools::install_github("awhstin/awtools")

look into tuquoise.pal


```{r}
library(car)

qqPlot(log(liz$burden + 1))

t.test(burden ~ location, data = liz)
liz$region <- as.factor(liz$region)
liz_aov <- aov(burden ~ region, data = liz)
summary(liz_aov)
library(multcomp)

TukeyHSD(liz_aov)

post_hoc <- glht(liz_aov, linfct = mcp(region = 'Tukey'))
summary(post_hoc)

confint(post_hoc)
cld(post_hoc)
plot(post_hoc)



plot(lm(log(burden +1) ~ region, data = liz))
summary(lm(log(burden +1) ~ location, data = liz))


mean(liz$burden[liz$region == "northern"], na.rm = TRUE)
mean(liz$burden[liz$region == "central"], na.rm = TRUE)
mean(liz$burden[liz$region == "southern"], na.rm = TRUE)

mean(liz$burden[liz$location == "inland"], na.rm = TRUE)
mean(liz$burden[liz$location == "coastal"], na.rm = TRUE)

ggplot(liz, aes(y = log(burden + 1), x = region)) +
    geom_boxplot(fill = "grey89",outlier.shape = NA) +
  geom_jitter(aes(color = reserve), alpha = .3) +
  theme_classic() +
  labs(x = "Region", y = "log(Lizard Burden + 1)",
       title = "Lizard burden by region") +
  theme(legend.text = element_text(size = 5))


ggplot(liz, aes(y = log(burden + 1), x = region)) +
    geom_boxplot(fill = "grey89",outlier.shape = NA) +
  geom_jitter(aes(color = reserve), alpha = .3) +
  facet_wrap(~month, ncol = 1)+
  theme_classic() +
  labs(x = "Region", y = "log(Lizard Burden + 1)",
       title = "Lizard burden by region") +
  theme(legend.text = element_text(size = 5))


ggplot(liz, aes(y = log(burden + 1), x = location)) +
    geom_boxplot(fill = "grey89",outlier.shape = NA) +
  geom_jitter(aes(color = reserve), alpha = .3) +
  theme_classic() +
  labs(x = "Region", y = "log(Lizard Burden + 1)",
       title = "Lizard burden by location") +
  theme(legend.text = element_text(size = 5))


liz %>%
  group_by(month) %>%
  summarise(freq = length(liz), .groups = 'drop')

liz_counts <-liz %>%
  group_by(reserve, month) %>%
  summarise(freq = length(liz), .groups = 'drop')

ggplot(liz_counts, aes(y = freq, x = reserve, fill = month)) +
  geom_histogram(stat = "identity")+
  scale_x_discrete(limits = rev(levels(liz_counts$reserve))) +
  coord_flip()

  
liz_counts_region <-liz %>%
  group_by(region, month) %>%
  summarise(freq = length(liz), .groups = 'drop')

ggplot(liz_counts_region, aes(y = freq, x = region,fill = month)) +
  geom_histogram(stat = "identity") +
  coord_flip()
  theme(axis.text.x = element_text(size = 5)) +
    coord_flip()



```

